### GET event by id
GET /v1/events/0674cb79-54af-794f-8000-14b298b8f5b6 HTTP/1.1
Host: localhost:8000


### GET all events with query parameters
GET /v1/events?page=0&limit=10 HTTP/1.1
Host: localhost:8000

